pipeline {
    agent { dockerfile true }
    parameters {
        string(name: 'Greeting', defaultValue: 'Hello', description: 'How should I greet the world?')
    }

    stages {
        stage('Build') {
            steps {
                echo "Building..  ${params.Greeting}"
            }
        }
        stage('Test') {
            steps {
                steps {
                echo 'Testing..'

                sh 'node --version'
                sh 'svn --version'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}
